# Tensors in torch

In [1]:
import torch

## 1. Creating tensors 

### Basics

Tensors can be created using specific commands:

In [2]:
torch.empty(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [3]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [4]:
torch.rand(1,3,1, dtype=torch.double)

tensor([[[0.4063],
         [0.9544],
         [0.9096]]], dtype=torch.float64)

Or directly from data:

In [5]:
torch.Tensor([[1,2,3]])

tensor([[1., 2., 3.]])

### `torch.Tensor` attributes

Each `torch.Tensor` object has three attributtes:
* `torch.dtype`
* `torch.device`
* `torch.layout`

#### `torch.dtype`

A `torch.dtype` is an object that represents the type of a `torch.Tensor`. There are **nine** different dtypes in torch:

| dtype  | alternative type |
|---|:---|
| torch.float32  | torch.float  |
| torch.float64  | torch.double  |
| torch.float16  | torch.half  |
| torch.uint8  | -  |
| torch.int8  | -  |
| torch.int32  | torch.int  |
| torch.int64  | torch.long  |
| torch.int16  | torch.short  |
| torch.bool  | -  |

#### `torch.device`

A `torch.device` is an object representing the device where the `torch.Tensor` is or will be allocated. Admits `cpu` or `cuda`, and the number to reference this resource. A `torch.device` admits the following notations:

```python
torch.device('cuda', 1)
torch.device('cuda:1')
```

#### `torch.layout`

A `torch.layout` is an object that represents the memory layout of a `torch.Tensor`: `torch.strided` for dense matrices or `torch.sparse_coo` for sparse matrices.

For a dense matrices, `torch.Tensor.stride()` is a list. In the k-th position of this list we can find the number of elements that must be skipped to jump to the next element the k-th dimension. For example:

In [6]:
x = torch.empty(3,2)
x

tensor([[1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [7]:
x.stride()

(2, 1)

This means: to jump to the next element in the first dimension (bi-dimensional arrays), we need to skip two elements. In the second dimension, only one element must be skipped to reach the following element.

In [8]:
x = torch.empty(3,2,2)
x

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [9]:
x.stride()

(4, 2, 1)

https://pytorch.org/docs/stable/tensor_attributes.html

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html